# Generated by Django 3.2.6 on 2021-08-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmCreation', '0002_auto_20210814_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='host',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(blank=True, default='pending_create', max_length=254, null=True),
        ),
    ]
