# Generated by Django 3.2.6 on 2021-08-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmCreation', '0003_auto_20210815_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, default='Up', max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmCreation.host'),
        ),
    ]
