# Generated by Django 3.2.6 on 2021-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmCreation', '0006_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
