# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('ram', models.CharField(blank=True, max_length=2, null=True)),
                ('cpu', models.CharField(blank=True, max_length=2, null=True)),
                ('storage', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
