# Generated by Django 3.2.6 on 2021-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmCreation', '0005_alter_server_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
