---

- name: install kvm virtualization packages
  apt:
      name: "{{ virtualization_packages }}"
      state: latest
      update_cache: yes
  when: ansible_os_family == "Debian"
  notify: start virtualiztion
